# Generated by Django 5.2.8 on 2025-11-24 04:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Listing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField()),
                ("description", models.TextField()),
                ("price_per_month", models.IntegerField()),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("number_of_roommates", models.IntegerField(blank=True)),
                ("address", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.TextField(blank=True)),
                ("display_name", models.TextField(blank=True)),
                ("email", models.TextField(blank=True)),
                ("phone_number", models.IntegerField(blank=True, null=True)),
                ("bio", models.TextField(blank=True)),
                (
                    "image_file",
                    models.ImageField(
                        blank=True, null=True, upload_to="profile_images/"
                    ),
                ),
                ("join_date", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="ListingPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image_url", models.URLField(blank=True)),
                (
                    "image_file",
                    models.ImageField(
                        blank=True, null=True, upload_to="listing_photos/"
                    ),
                ),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="project.listing",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="listing",
            name="lister",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="project.userprofile"
            ),
        ),
        migrations.CreateModel(
            name="InterestRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message_text", models.TextField()),
                ("submitted_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("declined", "Declined"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="project.listing",
                    ),
                ),
                (
                    "requester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="project.userprofile",
                    ),
                ),
            ],
        ),
    ]
